App_Progetto/App_Progetto/Models/Sensore.cs
namespace App_Progetto.Models
{
    public class Sensore
    {
        public Sensore()
        {
            Misuraziones = new List<Misurazione>();
        }
        public int Id { get; set; }

        required public bool StatoSensore { get; set; }

        required public string TipoSensore { get; set; }

        public int TerrenoId { get; set; } // Required foreign key property
        required public Terreno Terreno { get; set; } // Required reference navigation to principal

        public ICollection<Misurazione> Misuraziones { get; set; }

    }
}

App_Progetto/App_Progetto/Controllers/MisurazionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class MisurazionesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MisurazionesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Misuraziones
        public async Task<IActionResult> Index(int CodSensore)
        {
            var misurazioniSensore = _context.Misuraziones
                .Include(m => m.Sensores)
                .Where(m => m.Sensores.Id == CodSensore)
                .ToList();
            ViewData["codSensore"] = CodSensore;

            return View(misurazioniSensore);
        }

        // GET: Misuraziones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Misuraziones == null)
            {
                return NotFound();
            }

            var misurazione = await _context.Misuraziones
                .Include(m => m.Sensores)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (misurazione == null)
            {
                return NotFound();
            }

            return View(misurazione);
        }

        // GET: Misuraziones/Create
        public IActionResult Create(int CodSensore)
        {
            var tipoSensore = _context.Sensores
            .Where(s => s.Id == CodSensore)
            .Select(s => s.TipoSensore)
            .FirstOrDefault();

            //Console.WriteLine($"TipoSensore: {tipoSensore}");
            Console.WriteLine($"CodiceSensore nel metodo Create: {CodSensore}");

            ViewBag.CodiceSensore = CodSensore;
            ViewData["CodSensore"] = CodSensore;
            ViewData["TipoSensore"] = tipoSensore; 

            return View();
        }

        // POST: Misuraziones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DataOra,CodiceSensore,Valore,TipoMisurazione")] Misurazione misurazione)
        {
            Console.WriteLine("DataOra: " + misurazione.DataOra);
            Console.WriteLine("CodiceSensore: " + misurazione.CodiceSensore);
            Console.WriteLine("Valore: " + misurazione.Valore);
            Console.WriteLine("TipoMisurazione: " + misurazione.TipoMisurazione);
 
                ViewData["CodiceSensore"] = new SelectList(_context.Sensores, "Id", "Id", misurazione.CodiceSensore);
                Console.WriteLine("**********-->");
                _context.Add(misurazione);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                

            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine($"Error: {error.ErrorMessage}");
                }
            }
            return RedirectToAction("Index", new { CodSensore = misurazione.CodiceSensore });
            //return View(misurazione);
        }

        // GET: Misuraziones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Misuraziones == null)
            {
                return NotFound();
            }

            var misurazione = await _context.Misuraziones
                .Include(m => m.Sensores)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (misurazione == null)
            {
                return NotFound();
            }

            return View(misurazione);
        }

        // POST: Misuraziones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (_context.Misuraziones == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Misuraziones'  is null.");
            }
            var misurazione = await _context.Misuraziones.FindAsync(id);
            if (misurazione != null)
            {
                _context.Misuraziones.Remove(misurazione);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { CodSensore = misurazione.CodiceSensore });
        }


        // GET: Misuraziones/Edit/5
        public async Task<IActionResult> Edit(DateTime? id)
        {
            if (id == null || _context.Misuraziones == null)
            {
                return NotFound();
            }

            var misurazione = await _context.Misuraziones.FindAsync(id);
            if (misurazione == null)
            {
                return NotFound();
            }
            ViewData["CodiceSensore"] = new SelectList(_context.Sensores, "Id", "Id", misurazione.CodiceSensore);
            return View(misurazione);
        }

        // POST: Misuraziones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DateTime id, [Bind("DataOra,CodiceSensore,Valore,TipoMisurazione")] Misurazione misurazione)
        {
            if (id != misurazione.DataOra)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(misurazione);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MisurazioneExists(misurazione.DataOra))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodiceSensore"] = new SelectList(_context.Sensores, "Id", "Id", misurazione.CodiceSensore);
            return View(misurazione);
        }

        private bool MisurazioneExists(DateTime id)
        {
          return (_context.Misuraziones?.Any(e => e.DataOra == id)).GetValueOrDefault();
        }
    }
}

App_Progetto/App_Progetto/Controllers/TerrenoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class TerrenoesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _dbContext;
        private readonly ILogger<Controller> _logger;


        public TerrenoesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, ApplicationDbContext dbContext,
        ILogger<Controller> logger)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _dbContext = dbContext;
            _logger = logger;
        }

        // GET: Terrenoes
        public async Task<IActionResult> HomeTerreno()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var query = from terreno in _dbContext.Terrenos
                        join gestione in _dbContext.Gestiones on terreno.Id equals gestione.TerrenoId
                        where gestione.UserId == currentUser.Id
                        select new
                        {
                            TerrenoId = terreno.Id,
                            Foglio = terreno.Foglio,
                            Mappale = terreno.Mappale,
                            Ettari = terreno.Ettari,
                            Citta = terreno.CittaTerreno,
                            TipoColtura = terreno.TipoColtura,
                            TipoTerreno = terreno.TipoTerreno,
                            Ruolo = gestione.Ruolo
                            // Aggiungi altre proprietà se necessario
                        };

            var result = await query.ToListAsync();


            return View(result);
        }

        public async Task<IActionResult> VisualizzaTerreno(int TerrenoId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var terr = _dbContext.Terrenos.FirstOrDefault(t => t.Id == TerrenoId);
            List<String> NameCollab = new List<string>();

            if (terr == null)
                return NotFound();

            var Collaboratori = _dbContext.Gestiones
                .Where(g => g.TerrenoId == TerrenoId && g.Ruolo == "Collaboratore")
                .ToList();

            foreach (var collab in Collaboratori)
            {
                var user = await _userManager.FindByIdAsync(collab.UserId);
                NameCollab.Add(user.UserName);
            }
            //Console.WriteLine("ifuiru " + string.Join(", ", NameCollab));

            var gestione = _dbContext.Gestiones
                .FirstOrDefault(g => g.TerrenoId == terr.Id && g.UserId == currentUser.Id);

            string ruolo = gestione?.Ruolo ?? "Nessun ruolo associato";
            Console.WriteLine("********* " + ruolo);

            var viewModel = new
            {
                TerrenoId = terr.Id,
                Mappale = terr.Mappale,
                Foglio = terr.Foglio,
                Ettari = terr.Ettari,
                Citta = terr.CittaTerreno,
                TipoColtura = terr.TipoColtura,
                TipoTerreno = terr.TipoTerreno,
                Collaboratore = NameCollab,
                Ruolo = ruolo
            };

            return View(viewModel);
        }


        // GET: Terrenoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Terrenoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Mappale,Foglio,Ettari,CittaTerreno,TipoColtura,TipoTerreno")] Terreno terreno)
        {

                Console.WriteLine("Sto aggiungendo NUOVO Terreno");
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                Console.WriteLine($"UserId: {userId}");

                _dbContext.Add(terreno);
                await _dbContext.SaveChangesAsync();

                //CreateGestione();
            
                var datiGestione = new Gestione
                {
                    UserId = userId,
                    Ruolo = "Agricoltore",
                    TerrenoId = terreno.Id
                };
                
                _dbContext.Add(datiGestione);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(HomeTerreno));
               
        }

        //POST: per aggiungere nella Tabella Gestione, una nuova tupla,  
        public async Task<IActionResult> AggiungiCollaboratore(int terrenoId, string username)
        {
            Console.WriteLine("****Codice del Terreno ***** " + terrenoId);

            // Esempio di verifica (considera di implementare una logica più robusta):
            var user = _userManager.FindByNameAsync(username).Result;
            if (user != null)
            {
                var datiGestione = new Gestione
                {
                    UserId = user.Id,
                    Ruolo = "Collaboratore",
                    TerrenoId = terrenoId
                };

                _dbContext.Add(datiGestione);
                await _dbContext.SaveChangesAsync();
                TempData["Messaggio"] = "Collaboratore aggiunto con successo!";
                TempData["MessaggioTipo"] = "success";
            }
            else
            {
                TempData["Messaggio"] = "Username non trovato.";
                TempData["MessaggioTipo"] = "danger";
            }

            // Redirect alla vista originale
            return RedirectToAction("VisualizzaTerreno", new { TerrenoId = terrenoId });
        }


        // POST: per eliminare dalla Tabella Gestione una tupla relativa a un collaboratore
        [HttpPost]
        public async Task<IActionResult> EliminaCollaboratore(int terrenoId, string usernameToDelete)
        {
            Console.WriteLine("****Codice del Terreno ***** " + terrenoId);

            // Esempio di verifica (considera di implementare una logica più robusta):
            var userToDelete = await _userManager.FindByNameAsync(usernameToDelete);

            if (userToDelete != null)
            {
                // Cerca la tupla corrispondente nella tabella Gestione
                var datiGestioneToDelete = await _dbContext.Gestiones
                    .FirstOrDefaultAsync(g => g.TerrenoId == terrenoId && g.UserId == userToDelete.Id && g.Ruolo == "Collaboratore");

                if (datiGestioneToDelete != null)
                {
                    // Elimina la tupla dalla tabella Gestione
                    _dbContext.Gestiones.Remove(datiGestioneToDelete);
                    await _dbContext.SaveChangesAsync();
                    TempData["Messaggio"] = "Collaboratore eliminato con successo!";
                    TempData["MessaggioTipo"] = "success";
                }
                else
                {
                    TempData["Messaggio"] = "Collaboratore non trovato per il terreno specificato.";
                    TempData["MessaggioTipo"] = "danger";
                }
            }
            else
            {
                TempData["Messaggio"] = "Username del collaboratore da eliminare non trovato.";
                TempData["MessaggioTipo"] = "danger";
            }

            // Redirect alla vista originale
            return RedirectToAction("VisualizzaTerreno", new { TerrenoId = terrenoId });
        }


        //_________________________________________________________________


        // GET: Terrenoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _dbContext.Terrenos == null)
            {
                return NotFound();
            }

            var terreno = await _dbContext.Terrenos.FindAsync(id);
            if (terreno == null)
            {
                return NotFound();
            }
            return View(terreno);
        }

        // POST: Terrenoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Mappale,Foglio,Ettari,CittaTerreno,TipoColtura,TipoTerreno")] Terreno terreno)
        {
            if (id != terreno.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbContext.Update(terreno);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TerrenoExists(terreno.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(terreno);
        }

        // GET: Terrenoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _dbContext.Terrenos == null)
            {
                return NotFound();
            }

App_Progetto/App_Progetto/Views/Sensores/Create.cshtml
@model App_Progetto.Models.Sensore

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Sensore</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <p>Terreno: @ViewData["Mappale"] - @ViewData["Foglio"]</p>

                <input asp-for="TerrenoId" type="hidden" />
            </div>

            <div class="form-group">
                <label asp-for="TipoSensore" class="control-label"></label>
                <select asp-for="TipoSensore" class="form-control">
                    <option value="Umidità">Umidità</option>
                    <option value="Temperatura">Temperatura</option>
                    <option value="Luminosità">Luminosità</option>
                </select>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="StatoSensore" /> @Html.DisplayNameFor(model => model.StatoSensore)
                </label>
            </div>
            <br />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

App_Progetto/App_Progetto/Views/Sensores/Delete.cshtml
@model App_Progetto.Models.Sensore

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sensore</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatoSensore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatoSensore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoSensore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoSensore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Terreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Terreno.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    </form>
</div>

App_Progetto/App_Progetto/Views/Sensores/Details.cshtml
@model App_Progetto.Models.Sensore

@{
    ViewData["Title"] = "Details";
}

<h1>Dettagli Sensore</h1>

<div>
    <h4>Sensore</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatoSensore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatoSensore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoSensore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoSensore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Terreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Terreno.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
</div>

App_Progetto/App_Progetto/Views/Sensores/Edit.cshtml
@model App_Progetto.Models.Sensore

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sensore @Model.Id</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!--<input type="hidden" asp-for="Id" />-->
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="StatoSensore" /> @Html.DisplayNameFor(model => model.StatoSensore)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TipoSensore" class="control-label"></label>
                <input asp-for="TipoSensore" class="form-control" />
                <span asp-validation-for="TipoSensore" class="text-danger"></span>
            </div>
            <div class="form-group">
               <div>
                    <p>Mappale - Foglio: @ViewData["Mappale"] - @ViewData["Foglio"]</p>
                    <br />
            </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

App_Progetto/App_Progetto/Views/Sensores/Index.cshtml
@using System.Security.Claims;
@model IEnumerable<App_Progetto.Models.Sensore>

@{
    ViewData["Title"] = "Index";
}


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatoSensore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoSensore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Terreno.Mappale)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Terreno.Foglio)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatoSensore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoSensore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Terreno.Mappale)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Terreno.Foglio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                @if (item.Terreno.Gestiones.Any(g => g.UserId == User.FindFirst(ClaimTypes.NameIdentifier)?.Value && g.Ruolo == "Agricoltore"))
                {
                    <a asp-action="Delete" asp-route-id="@item.Id"> Delete</a>
                }
            </td>
            <td>
                <a class="btn btn-outline-success" style="background-color: #9FE2BF; color: #000;" asp-controller="Misuraziones"
                asp-action="Index" asp-route-CodSensore="@item.Id">Misurazioni</a>
            </td>
        </tr>
}
    </tbody>
</table>

App_Progetto/App_Progetto/Views/Sensores/SensoriDettaglio.cshtml
@{
    ViewData["Title"] = "SensoriDettaglio";
}

<h1>Dettaglio Sensori</h1>

<table class="table table-striped mt-4">
    <thead>
        <tr class="bg-success text-white">
            <th>TerrenoId</th>
            <th>Mappale</th>
            <th>Foglio</th>
            <th>IdSensore</th>
            <th>StatoSensore</th>
            <th>TipoSensore</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var terr in Model)
        {
            <tr>
                <td>@terr.TerrenoId</td>
                <td>@terr.Mappale</td>
                <td>@terr.Foglio</td>
                <td>@terr.Id</td>
                <td>
                    @if (terr.StatoSensore)
                    {
                        <input checked="checked" class="check-box" disabled="disabled" type="checkbox">
                    }
                    else
                    {
                        <input class="check-box" disabled="disabled" type="checkbox">
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@terr.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@terr.Id">Details</a> |
                    @if (terr.Ruolo == "Agricoltore")
                    {
                        <a asp-action="Delete" asp-route-id="@terr.Id">|Delete </a>
                    }
                </td>
                <td>
                    <a class="btn btn-outline-success" style="background-color: #9FE2BF; color: #000;" asp-controller="Misuraziones"
                   asp-action="Index" asp-route-CodSensore="@terr.Id">Misurazioni</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn action-button text-white" asp-controller="Terrenoes" asp-action="VisualizzaTerreno" asp-route-TerrenoId="@ViewData["IdTerreno"]" style="background-color: dodgerblue">Ritorna indietro</a>
</div>