App_Progetto/App_Progetto/Controllers/AttuatoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Humanizer;
using System.Security.Claims;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class AttuatoresController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly ILogger<Controller> _logger;


        public AttuatoresController(UserManager<IdentityUser> userManager, ApplicationDbContext context, ILogger<Controller> logger)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        [Authorize(Roles = "Agricoltore,Collaboratore")]
        public async Task<IActionResult> AttDettaglio(int TerrenoId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var gestione = _context.Gestiones
                .FirstOrDefault(g => g.TerrenoId == TerrenoId && g.UserId == currentUser.Id);

            string ruolo = gestione?.Ruolo ?? "Nessun ruolo associato";
            
            var query = from a in _context.Attuatores
                        join t in _context.Terrenos on a.TerrenoId equals t.Id
                        where a.TerrenoId == TerrenoId
                        select new
                        {
                            TerrenoId = a.TerrenoId,
                            Mappale = t.Mappale,
                            Foglio = t.Foglio,
                            Id = a.Id,
                            TipoAttuatore = a.TipoAttuatore,
                            Standby = a.Standby,
                            Attivazione = a.Attivazione,
                            Ruolo = ruolo
                        };
            ViewData["IdTerreno"] = TerrenoId;
            var result = await query.ToListAsync();
            foreach (var item in result)
            {
                Console.WriteLine($"TerrenoId: {item.TerrenoId}, Foglio: {item.Foglio}, Mappale: {item.Mappale}, TipoAttuatore: {item.TipoAttuatore}, Standby: {item.Standby}, Attivazione: {item.Attivazione}");
            }
            return View(result);
        }

        //[Authorize(Roles = "Agricoltore,Collaboratore")]
        // GET: Attuatores

        public async Task<IActionResult> Index()
        {
            // Ottenere l'ID dell'utente corrente
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            var attuatoriUtente = _context.Attuatores
                .Include(a => a.Terreno)  // Includi il riferimento al Terreno
                .ThenInclude(t => t.Gestiones)  // Assicurati di includere le Gestiones
                .Where(a => a.Terreno.Gestiones.Any(g => g.UserId == userId))
                .ToList();

            return View(attuatoriUtente);
        }

        // GET: Attuatores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Attuatores == null)
            {
                return NotFound();
            }

            var attuatore = await _context.Attuatores
                .Include(a => a.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attuatore == null)
            {
                return NotFound();
            }

            return View(attuatore);
        }

        // GET: Attuatores/Create
        public IActionResult Create(int TerrenoId)
        {
            // Imposta il TerrenoId nella ViewBag (o ovunque tu preferisca passare dati alla vista)
            var terreno = _context.Terrenos.Find(TerrenoId);

            ViewBag.TerrenoId = TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio;

            return View();
        }

        // POST: Attuatores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TipoAttuatore,Standby,Attivazione,TerrenoId")] Attuatore attuatore)
        {
            _context.Add(attuatore);
            await _context.SaveChangesAsync();
            /*return RedirectToAction(nameof(Index));*/
            //return RedirectToAction("AttDettaglio", new { TerrenoId = attuatore.TerrenoId });
            return RedirectToAction("Create", "Pianoes", new { TerrenoId = attuatore.TerrenoId });
        }

        // GET: Attuatores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Attuatores == null)
            {
                return NotFound();
            }

            var attuatore = await _context.Attuatores.FindAsync(id);
            if (attuatore == null)
            {
                return NotFound();
            }

            var terreno = await _context.Terrenos.FindAsync(attuatore.TerrenoId);

            // Passa TerrenoId e i dati del Terreno alla vista
            ViewData["TerrenoId"] = attuatore.TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio; 
            
            return View(attuatore);
        }

        // POST: Attuatores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Attuatores/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TipoAttuatore,Standby,Attivazione,TerrenoId")] Attuatore attuatore)
        {
            if (id != attuatore.Id)
            {
                return NotFound();
            }
            _context.Update(attuatore);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Attuatores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Attuatores == null)
            {
                return NotFound();
            }

            var attuatore = await _context.Attuatores
                .Include(a => a.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attuatore == null)
            {
                return NotFound();
            }

            return View(attuatore);
        }

        // POST: Attuatores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Attuatores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Attuatores'  is null.");
            }
            var attuatore = await _context.Attuatores.FindAsync(id);
            if (attuatore != null)
            {
                _context.Attuatores.Remove(attuatore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttuatoreExists(int id)
        {
          return (_context.Attuatores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

App_Progetto/App_Progetto/Controllers/SensoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Humanizer;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class SensoresController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly ILogger<Controller> _logger;

        public SensoresController(UserManager<IdentityUser> userManager, ApplicationDbContext context, ILogger<Controller> logger)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        //Creo il task per la visualizzazione dei sensori
        public async Task<IActionResult> SensoriDettaglio(int TerrenoId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var gestione = _context.Gestiones
                .FirstOrDefault(g => g.TerrenoId == TerrenoId && g.UserId == currentUser.Id);

            string ruolo = gestione?.Ruolo ?? "Nessun ruolo associato";
            Console.WriteLine("********* " + ruolo);

            var query = from a in _context.Sensores
                        join t in _context.Terrenos on a.TerrenoId equals t.Id
                        where a.TerrenoId == TerrenoId
                        select new
                        {
                            TerrenoId = a.TerrenoId,
                            Foglio = t.Foglio,
                            Mappale = t.Mappale,
                            Id = a.Id,
                            StatoSensore = a.StatoSensore,
                            TipoSensore = a.TipoSensore, 
                            Ruolo = ruolo
                        };
            ViewData["IdTerreno"] = TerrenoId;
            var result = await query.ToListAsync();
            foreach (var item in result)
            {
                Console.WriteLine($"TerrenoId: {item.TerrenoId}, Foglio: {item.Foglio}, Mappale: {item.Mappale}, SensoreId: {item.Id}, Stato Sensore: {item.StatoSensore}, Tipo Sensore: {item.TipoSensore}");
            }
            return View(result);
        }



        // GET: Sensores
        /*public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Sensores.Include(s => s.Terreno);
            return View(await applicationDbContext.ToListAsync());
        }*/
        [Authorize(Roles = "Agricoltore,Collaboratore")]
        public async Task<IActionResult> Index()
        {
            // Ottenere l'ID dell'utente corrente
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var sensoriUtente = _context.Sensores
                .Include(a => a.Terreno)  // Includi il riferimento al Terreno
                .ThenInclude(t => t.Gestiones)  // Assicurati di includere le Gestiones
                .Where(a => a.Terreno.Gestiones.Any(g => g.UserId == userId))
                .ToList();

            return View(sensoriUtente);
        }


        // GET: Sensores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sensores == null)
            {
                return NotFound();
            }

            var sensore = await _context.Sensores
                .Include(s => s.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sensore == null)
            {
                return NotFound();
            }

            return View(sensore);
        }

        // GET: Sensores/Create
        public IActionResult Create(int TerrenoId)
        {
            var terreno = _context.Terrenos.Find(TerrenoId);
            
            ViewBag.TerrenoId = TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio;

            return View();
        }

        // POST: Sensores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StatoSensore,TipoSensore,TerrenoId")] Sensore sensore)
        {
            _context.Add(sensore);
            await _context.SaveChangesAsync();
            return RedirectToAction("SensoriDettaglio", new { TerrenoId = sensore.TerrenoId });
        }

        // GET: Sensores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sensores == null)
            {
                return NotFound();
            }

            var sensore = await _context.Sensores.FindAsync(id);
            if (sensore == null)
            {
                return NotFound();
            }

            var terreno = await _context.Terrenos.FindAsync(sensore.TerrenoId);

            // Passa TerrenoId e i dati del Terreno alla vista
            ViewData["TerrenoId"] = sensore.TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio;

            return View(sensore);
        }

        // POST: Sensores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StatoSensore,TipoSensore,TerrenoId")] Sensore sensore)
        {
            if (id != sensore.Id)
            {
                return NotFound();
            }
            _context.Update(sensore);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Sensores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sensores == null)
            {
                return NotFound();
            }

            var sensore = await _context.Sensores
                .Include(s => s.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sensore == null)
            {
                return NotFound();
            }

            return View(sensore);
        }

        // POST: Sensores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sensores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Sensores'  is null.");
            }
            var sensore = await _context.Sensores.FindAsync(id);
            if (sensore != null)
            {
                _context.Sensores.Remove(sensore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SensoreExists(int id)
        {
          return (_context.Sensores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

App_Progetto/App_Progetto/Views/User/HomeTerreno.cshtml
@{
    ViewData["Title"] = "HomeTerreno";
}
@if (User.IsInRole("Agricoltore"))
{
    <h2>Visualizza Miei Terreni (da Agricoltore)</h2>

    <table class="table table-striped mt-4">
        <thead>
            <tr class="bg-success text-white">
                <th>Foglio</th>
                <th>Mappale</th>
                <th>Ettari</th>
                <th>Città</th>
                <th>Coltura</th>
                <th>Tipo Terreno</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var terr in Model)
            {
                @if ("Agricoltore" == terr.Ruolo)
                {
                    <tr>
                        <td>@terr.Foglio</td>
                        <td>@terr.Mappale</td>
                        <td>@terr.Ettari</td>
                        <td>@terr.Citta</td>
                        <td>@terr.TipoColtura</td>
                        <td>@terr.TipoTerreno</td>
                        <td>
                            <a class="btn btn-outline-success" style="background-color: #9FE2BF; color: #000;" asp-controller="User"
                            asp-action= "VisualizzaTerreno" asp-route-TerrenoId="@terr.TerrenoId">Visualizza</a>
                        </td>

                    </tr>
                }

            }
        </tbody>
        </table>
} 
@if (User.IsInRole("Collaboratore"))
{
        <h2>Visualizza Terreni Gestisco (da Collaboratore)</h2>

        <table class="table table-striped mt-4">
            <thead>
            <tr class="bg-success text-white">
                    <th>Foglio</th>
                    <th>Mappale</th>
                    <th>Ettari</th>
                    <th>Città</th>
                    <th>Coltura</th>
                    <th>Tipo Terreno</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var terr in Model)
            {@if ("Collaboratore" == terr.Ruolo)
                {
                    <tr>
                        <td>@terr.Foglio</td>
                        <td>@terr.Mappale</td>
                        <td>@terr.Ettari</td>
                        <td>@terr.Citta</td>
                        <td>@terr.TipoColtura</td>
                        <td>@terr.TipoTerreno</td>
                        <td>
                            <a class="btn btn-outline-success" style="background-color: #9FE2BF; color: #000;" asp-controller="User"
                            asp-action="VisualizzaTerreno" asp-route-TerrenoId="@terr.TerrenoId">Visualizza</a>
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
    }

App_Progetto/App_Progetto/Views/User/VisualizzaTerreno.cshtml
@{
    ViewData["Title"] = "VisualizzaTerreno";
}
<style>
    .tableTerr {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    th {
      background-color: #f2f2f2;
    }
  </style>

<h1>Pagina del Terreno</h1>

<div id="main-container">
    <div class="row row-table" id="content-container">
        <div class="col" id="info-container">
            <table class="table table-striped" id="tableTerr">
                <tbody>
                    <tr>
                        <th>Foglio</th>
                        <td>@Model.Foglio</td>
                    </tr>
                    <tr>
                        <th>Mappale</th>
                        <td>@Model.Mappale</td>
                    </tr>
                    <tr>
                        <th>Ettari</th>
                        <td>@Model.Ettari</td>
                    </tr>
                    <tr>
                        <th>Citta</th>
                        <td>@Model.Citta</td>
                    </tr>
                    <tr>
                        <th>TipoColtura</th>
                        <td>@Model.TipoColtura</td>
                    </tr>
                    <tr>
                        <th>TipoTerreno</th>
                        <td>@Model.TipoTerreno</td>
                    </tr>
                    <tr>
                        <th>Collaboratore</th>
                        <td>@string.Join(" , ", Model.Collaboratore)</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col">
            <div id="delete-button-container">
                @if (Model.Ruolo == "Agricoltore")
                {
                    <div class="row row-table">
                        <button class="action-button" id="delete-button" style="background-color: #4CAF50; margin-bottom: 10px;">Elimina terreno</button>
                    </div>
                }
                <div class="row row-table">
                    <a class="btn action-button" asp-controller="Attuatores" asp-action="Create" asp-route-TerrenoId="@Model.TerrenoId" style="background-color: orange;">Aggiungi attuatore</a>
                </div>
                <div class="row row-table">
                    <a class="btn action-button" asp-controller="Sensores" asp-action="Create" asp-route-TerrenoId="@Model.TerrenoId" style="background-color: orange;">Aggiungi sensore</a>
                </div>
            </div>
        </div>
    </div>

    <div id="buttons-container">
        <!-- Bottoni Attuatori e Sensori -->
        <a class="btn action-button" asp-controller="Attuatores" asp-action="AttDettaglio" asp-route-TerrenoId="@Model.TerrenoId">Attuatori</a>

        <a class="btn action-button" asp-controller="Sensores" asp-action="SensoriDettaglio" asp-route-TerrenoId="@Model.TerrenoId">Sensori</a>
    </div>
</div>