App_Progetto/App_Progetto/Controllers/SensoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Humanizer;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class SensoresController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly ILogger<Controller> _logger;

        public SensoresController(UserManager<IdentityUser> userManager, ApplicationDbContext context, ILogger<Controller> logger)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        //Creo il task per la visualizzazione dei sensori
        public async Task<IActionResult> SensoriDettaglio(int TerrenoId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var gestione = _context.Gestiones
                .FirstOrDefault(g => g.TerrenoId == TerrenoId && g.UserId == currentUser.Id);

            string ruolo = gestione?.Ruolo ?? "Nessun ruolo associato";
            Console.WriteLine("********* " + ruolo);

            var query = from a in _context.Sensores
                        join t in _context.Terrenos on a.TerrenoId equals t.Id
                        where a.TerrenoId == TerrenoId
                        select new
                        {
                            TerrenoId = a.TerrenoId,
                            Foglio = t.Foglio,
                            Mappale = t.Mappale,
                            Id = a.Id,
                            StatoSensore = a.StatoSensore,
                            TipoSensore = a.TipoSensore, 
                            Ruolo = ruolo
                        };
            ViewData["IdTerreno"] = TerrenoId;
            var result = await query.ToListAsync();
            foreach (var item in result)
            {
                Console.WriteLine($"TerrenoId: {item.TerrenoId}, Foglio: {item.Foglio}, Mappale: {item.Mappale}, SensoreId: {item.Id}, Stato Sensore: {item.StatoSensore}, Tipo Sensore: {item.TipoSensore}");
            }
            return View(result);
        }



        // GET: Sensores
        /*public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Sensores.Include(s => s.Terreno);
            return View(await applicationDbContext.ToListAsync());
        }*/
        [Authorize(Roles = "Agricoltore,Collaboratore")]
        public async Task<IActionResult> Index()
        {
            // Ottenere l'ID dell'utente corrente
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var sensoriUtente = _context.Sensores
                .Include(a => a.Terreno)  // Includi il riferimento al Terreno
                .ThenInclude(t => t.Gestiones)  // Assicurati di includere le Gestiones
                .Where(a => a.Terreno.Gestiones.Any(g => g.UserId == userId))
                .ToList();

            return View(sensoriUtente);
        }


        // GET: Sensores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sensores == null)
            {
                return NotFound();
            }

            var sensore = await _context.Sensores
                .Include(s => s.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sensore == null)
            {
                return NotFound();
            }

            return View(sensore);
        }

        // GET: Sensores/Create
        public IActionResult Create(int TerrenoId)
        {
            var terreno = _context.Terrenos.Find(TerrenoId);
            
            ViewBag.TerrenoId = TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio;

            return View();
        }

        // POST: Sensores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StatoSensore,TipoSensore,TerrenoId")] Sensore sensore)
        {
            _context.Add(sensore);
            await _context.SaveChangesAsync();
            return RedirectToAction("SensoriDettaglio", new { TerrenoId = sensore.TerrenoId });
        }

        // GET: Sensores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sensores == null)
            {
                return NotFound();
            }

            var sensore = await _context.Sensores.FindAsync(id);
            if (sensore == null)
            {
                return NotFound();
            }

            var terreno = await _context.Terrenos.FindAsync(sensore.TerrenoId);

            // Passa TerrenoId e i dati del Terreno alla vista
            ViewData["TerrenoId"] = sensore.TerrenoId;
            ViewData["Mappale"] = terreno?.Mappale;
            ViewData["Foglio"] = terreno?.Foglio;

            return View(sensore);
        }

        // POST: Sensores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StatoSensore,TipoSensore,TerrenoId")] Sensore sensore)
        {
            if (id != sensore.Id)
            {
                return NotFound();
            }
            _context.Update(sensore);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Sensores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sensores == null)
            {
                return NotFound();
            }

            var sensore = await _context.Sensores
                .Include(s => s.Terreno)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sensore == null)
            {
                return NotFound();
            }

            return View(sensore);
        }

        // POST: Sensores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sensores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Sensores'  is null.");
            }
            var sensore = await _context.Sensores.FindAsync(id);
            if (sensore != null)
            {
                _context.Sensores.Remove(sensore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SensoreExists(int id)
        {
          return (_context.Sensores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

App_Progetto/App_Progetto/Controllers/TerrenoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Progetto.Data;
using App_Progetto.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace App_Progetto.Controllers
{
    [Authorize(Roles = "Agricoltore,Collaboratore")]
    public class TerrenoesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _dbContext;
        private readonly ILogger<Controller> _logger;


        public TerrenoesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, ApplicationDbContext dbContext,
        ILogger<Controller> logger)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _dbContext = dbContext;
            _logger = logger;
        }

        // GET: Terrenoes
        public async Task<IActionResult> HomeTerreno()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var query = from terreno in _dbContext.Terrenos
                        join gestione in _dbContext.Gestiones on terreno.Id equals gestione.TerrenoId
                        where gestione.UserId == currentUser.Id
                        select new
                        {
                            TerrenoId = terreno.Id,
                            Foglio = terreno.Foglio,
                            Mappale = terreno.Mappale,
                            Ettari = terreno.Ettari,
                            Citta = terreno.CittaTerreno,
                            TipoColtura = terreno.TipoColtura,
                            TipoTerreno = terreno.TipoTerreno,
                            Ruolo = gestione.Ruolo
                            // Aggiungi altre proprietà se necessario
                        };

            var result = await query.ToListAsync();


            return View(result);
        }

        public async Task<IActionResult> VisualizzaTerreno(int TerrenoId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var terr = _dbContext.Terrenos.FirstOrDefault(t => t.Id == TerrenoId);
            List<String> NameCollab = new List<string>();

            if (terr == null)
                return NotFound();

            var Collaboratori = _dbContext.Gestiones
                .Where(g => g.TerrenoId == TerrenoId && g.Ruolo == "Collaboratore")
                .ToList();

            foreach (var collab in Collaboratori)
            {
                var user = await _userManager.FindByIdAsync(collab.UserId);
                NameCollab.Add(user.UserName);
            }
            //Console.WriteLine("ifuiru " + string.Join(", ", NameCollab));

            var gestione = _dbContext.Gestiones
                .FirstOrDefault(g => g.TerrenoId == terr.Id && g.UserId == currentUser.Id);

            string ruolo = gestione?.Ruolo ?? "Nessun ruolo associato";
            Console.WriteLine("********* " + ruolo);

            var viewModel = new
            {
                TerrenoId = terr.Id,
                Mappale = terr.Mappale,
                Foglio = terr.Foglio,
                Ettari = terr.Ettari,
                Citta = terr.CittaTerreno,
                TipoColtura = terr.TipoColtura,
                TipoTerreno = terr.TipoTerreno,
                Collaboratore = NameCollab,
                Ruolo = ruolo
            };

            return View(viewModel);
        }


        // GET: Terrenoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Terrenoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Mappale,Foglio,Ettari,CittaTerreno,TipoColtura,TipoTerreno")] Terreno terreno)
        {

                Console.WriteLine("Sto aggiungendo NUOVO Terreno");
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                Console.WriteLine($"UserId: {userId}");

                _dbContext.Add(terreno);
                await _dbContext.SaveChangesAsync();

                //CreateGestione();
            
                var datiGestione = new Gestione
                {
                    UserId = userId,
                    Ruolo = "Agricoltore",
                    TerrenoId = terreno.Id
                };
                
                _dbContext.Add(datiGestione);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(HomeTerreno));
               
        }

        //POST: per aggiungere nella Tabella Gestione, una nuova tupla,  
        public async Task<IActionResult> AggiungiCollaboratore(int terrenoId, string username)
        {
            Console.WriteLine("****Codice del Terreno ***** " + terrenoId);

            // Esempio di verifica (considera di implementare una logica più robusta):
            var user = _userManager.FindByNameAsync(username).Result;
            if (user != null)
            {
                var datiGestione = new Gestione
                {
                    UserId = user.Id,
                    Ruolo = "Collaboratore",
                    TerrenoId = terrenoId
                };

                _dbContext.Add(datiGestione);
                await _dbContext.SaveChangesAsync();
                TempData["Messaggio"] = "Collaboratore aggiunto con successo!";
                TempData["MessaggioTipo"] = "success";
            }
            else
            {
                TempData["Messaggio"] = "Username non trovato.";
                TempData["MessaggioTipo"] = "danger";
            }

            // Redirect alla vista originale
            return RedirectToAction("VisualizzaTerreno", new { TerrenoId = terrenoId });
        }


        // POST: per eliminare dalla Tabella Gestione una tupla relativa a un collaboratore
        [HttpPost]
        public async Task<IActionResult> EliminaCollaboratore(int terrenoId, string usernameToDelete)
        {
            Console.WriteLine("****Codice del Terreno ***** " + terrenoId);

            // Esempio di verifica (considera di implementare una logica più robusta):
            var userToDelete = await _userManager.FindByNameAsync(usernameToDelete);

            if (userToDelete != null)
            {
                // Cerca la tupla corrispondente nella tabella Gestione
                var datiGestioneToDelete = await _dbContext.Gestiones
                    .FirstOrDefaultAsync(g => g.TerrenoId == terrenoId && g.UserId == userToDelete.Id && g.Ruolo == "Collaboratore");

                if (datiGestioneToDelete != null)
                {
                    // Elimina la tupla dalla tabella Gestione
                    _dbContext.Gestiones.Remove(datiGestioneToDelete);
                    await _dbContext.SaveChangesAsync();
                    TempData["Messaggio"] = "Collaboratore eliminato con successo!";
                    TempData["MessaggioTipo"] = "success";
                }
                else
                {
                    TempData["Messaggio"] = "Collaboratore non trovato per il terreno specificato.";
                    TempData["MessaggioTipo"] = "danger";
                }
            }
            else
            {
                TempData["Messaggio"] = "Username del collaboratore da eliminare non trovato.";
                TempData["MessaggioTipo"] = "danger";
            }

            // Redirect alla vista originale
            return RedirectToAction("VisualizzaTerreno", new { TerrenoId = terrenoId });
        }


        //_________________________________________________________________


        // GET: Terrenoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _dbContext.Terrenos == null)
            {
                return NotFound();
            }

            var terreno = await _dbContext.Terrenos.FindAsync(id);
            if (terreno == null)
            {
                return NotFound();
            }
            return View(terreno);
        }

        // POST: Terrenoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Mappale,Foglio,Ettari,CittaTerreno,TipoColtura,TipoTerreno")] Terreno terreno)
        {
            if (id != terreno.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbContext.Update(terreno);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TerrenoExists(terreno.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(terreno);
        }

        // GET: Terrenoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _dbContext.Terrenos == null)
            {
                return NotFound();
            }

App_Progetto/App_Progetto/Views/Terrenoes/Create.cshtml
@model App_Progetto.Models.Terreno

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Terreno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
         <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Mappale" class="control-label"></label>
                <input asp-for="Mappale" class="form-control" />
                <span asp-validation-for="Mappale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foglio" class="control-label"></label>
                <input asp-for="Foglio" class="form-control" />
                <span asp-validation-for="Foglio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ettari" class="control-label"></label>
                <input asp-for="Ettari" class="form-control" />
                <span asp-validation-for="Ettari" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CittaTerreno" class="control-label"></label>
                <input asp-for="CittaTerreno" class="form-control" />
                <span asp-validation-for="CittaTerreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoColtura" class="control-label"></label>
                <input asp-for="TipoColtura" class="form-control" />
                <span asp-validation-for="TipoColtura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="TipoTerreno" class="form-control">
                    <option value="Serra">Serra</option>
                    <option value="Campo">Campo</option>
                </select>
            <div class="form-group">
                <label asp-for="TipoColtura" class="control-label"></label>
            </div>
                <span asp-validation-for="TipoTerreno" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

App_Progetto/App_Progetto/Views/Terrenoes/Details.cshtml
@model App_Progetto.Models.Terreno

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Terreno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mappale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mappale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foglio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foglio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ettari)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ettari)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CittaTerreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CittaTerreno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoColtura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoColtura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoTerreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoTerreno)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

App_Progetto/App_Progetto/Views/Terrenoes/HomeTerreno.cshtml
@{
    ViewData["Title"] = "HomeTerreno";
}
@if (User.IsInRole("Agricoltore"))
{
    <div class="row-table-create text-right justify-content-end align-items-end">
        <a class="btn action-button-create" asp-controller="Terrenoes" asp-action="Create" style="background-color: #4CAF50; margin-bottom: 10px;">Aggiungi terreno</a>
    </div>

    <h2>Visualizza Miei Terreni (da Agricoltore)</h2>

    <table class="table table-striped mt-4">
        <thead>
            <tr class="bg-success text-white">
                <th>Mappale</th>
                <th>Foglio</th>
                <th>Ettari</th>
                <th>Città</th>
                <th>Coltura</th>
                <th>Tipo Terreno</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var terr in Model)
            {
                @if ("Agricoltore" == terr.Ruolo)
                {
                    <tr>
                        <td>@terr.Mappale</td>
                        <td>@terr.Foglio</td>
                        <td>@terr.Ettari</td>
                        <td>@terr.Citta</td>
                        <td>@terr.TipoColtura</td>
                        <td>@terr.TipoTerreno</td>
                        <td>
                            <a class="btn btn-outline-success" style="background-color: #9FE2BF; color: #000;" asp-controller="Terrenoes"
                            asp-action= "VisualizzaTerreno" asp-route-TerrenoId="@terr.TerrenoId">Visualizza</a>
                        </td>

                    </tr>
                }

            }
        </tbody>
        </table>
} 
@if (User.IsInRole("Collaboratore"))
{
        <h2>Visualizza Terreni Gestisco (da Collaboratore)</h2>

        <table class="table table-striped mt-4">
            <thead>
            <tr class="bg-success text-white">
                    <th>Foglio</th>
                    <th>Mappale</th>
                    <th>Ettari</th>
                    <th>Città</th>
                    <th>Coltura</th>
                    <th>Tipo Terreno</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var terr in Model)
            {@if ("Collaboratore" == terr.Ruolo)
                {
                    <tr>
                        <td>@terr.Foglio</td>
                        <td>@terr.Mappale</td>
                        <td>@terr.Ettari</td>
                        <td>@terr.Citta</td>
                        <td>@terr.TipoColtura</td>
                        <td>@terr.TipoTerreno</td>
                        <td>
                            <a class="btn btn-outline-success" style="background-color: #9FE2BF; color: #000;" asp-controller="Terrenoes"
                            asp-action="VisualizzaTerreno" asp-route-TerrenoId="@terr.TerrenoId">Visualizza</a>
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
    }

App_Progetto/App_Progetto/Views/Terrenoes/VisualizzaTerreno.cshtml
@{
    ViewData["Title"] = "VisualizzaTerreno";
}

<style>
    .tableTerr {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    th {
      background-color: #f2f2f2;
    }
</style>

<h1>Pagina del Terreno</h1>

@if (TempData.ContainsKey("Messaggio") && TempData.ContainsKey("MessaggioTipo"))
{
    var messaggio = TempData["Messaggio"] as string;
    var messaggioTipo = TempData["MessaggioTipo"] as string;

    <div class="alert alert-@messaggioTipo" role="alert">
        @messaggio
    </div>

    <script>
        setTimeout(function () {
            document.getElementById('messaggioAlert').style.display = 'none';
        }, 6000);
    </script>
}

<div id="main-container">
    <div class="row row-table" id="content-container">
        <div class="col" id="info-container">
            <table class="table table-striped" id="tableTerr">
                <tbody>
                    <tr>
                        <th>Mappale</th>
                        <td>@Model.Mappale</td>
                    </tr>
                    <tr>
                        <th>Foglio</th>
                        <td>@Model.Foglio</td>
                    </tr>
                    <tr>
                        <th>Ettari</th>
                        <td>@Model.Ettari</td>
                    </tr>
                    <tr>
                        <th>Citta</th>
                        <td>@Model.Citta</td>
                    </tr>
                    <tr>
                        <th>TipoColtura</th>
                        <td>@Model.TipoColtura</td>
                    </tr>
                    <tr>
                        <th>TipoTerreno</th>
                        <td>@Model.TipoTerreno</td>
                    </tr>
                    <tr>
                        <th>Collaboratore</th>
                        <td>@string.Join(" , ", Model.Collaboratore)</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col">
            <div id="delete-button-container">
                @if (Model.Ruolo == "Agricoltore")
                {
                    <div class="row row-table">
                        <a class="btn btn-lg action-button delete-button text-white" asp-controller="Terrenoes" asp-action="Delete" asp-route-id="@Model.TerrenoId" style="background-color: #DC143C; margin-bottom: 10px;">Elimina Terreno</a>
                    </div>

                    <div class="row row-table">
                        <a class="btn btn-lg action-button text-white" id="AggCollab-button" style="background-color: #4CAF50; margin-bottom: 10px;" data-toggle="modal" data-target="#aggiungiCollaboratoreModal">Aggiungi Collaboratore</a>
                    </div>

                    <div class="row row-table">
                        <a class="btn btn-lg action-button delete-button text-white" id="ElimCollab-button" style="background-color: #DC143C; margin-bottom: 10px;" data-toggle="modal" data-target="#eliminaCollaboratoreModal">Elimina Collaboratore</a>
                    </div>
                }
                <div class="row row-table">
                    <a class="btn btn-lg action-button text-white" asp-controller="Attuatores" asp-action="Create" asp-route-TerrenoId="@Model.TerrenoId" style="background-color: orange; margin-bottom: 10px;">Aggiungi attuatore</a>
                </div>
                <div class="row row-table">
                    <a class="btn btn-lg action-button text-white" asp-controller="Sensores" asp-action="Create" asp-route-TerrenoId="@Model.TerrenoId" style="background-color: orange; margin-bottom: 10px;">Aggiungi sensore</a>
                </div>
            </div>
        </div>

        <div id="buttons-container" class="d-flex justify-content-center align-items-center">
            <!-- Bottoni Attuatori e Sensori -->
            <a class="btn btn-lg action-button text-white mb-3" asp-controller="Attuatores" asp-action="AttDettaglio" asp-route-TerrenoId="@Model.TerrenoId" style="background-color: #4CAF50; margin-right: 10px;">Attuatori</a>

            <a class="btn btn-lg action-button text-white mb-3" asp-controller="Sensores" asp-action="SensoriDettaglio" asp-route-TerrenoId="@Model.TerrenoId" style="background-color: #4CAF50; margin-left: 10px;">Sensori</a>
        </div>


    </div>
</div>

<!-- Aggiungi questo dove vuoi mostrare il Modal -->
<div class="modal fade" id="aggiungiCollaboratoreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aggiungi Collaboratore</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Form per inserire il nome utente del collaboratore -->
                <form asp-action="AggiungiCollaboratore" asp-controller="Terrenoes" method="post">
                    <input type="hidden" name="terrenoId" value="@Model.TerrenoId" />
                    <div class="form-group">
                        <label for="username">Nome Utente Collaboratore:</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary">Aggiungi</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="eliminaCollaboratoreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Elimina Collaboratore</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Form per inserire il nome utente del collaboratore da eliminare -->
                <form asp-action="EliminaCollaboratore" asp-controller="Terrenoes" method="post">
                    <input type="hidden" name="terrenoId" value="@Model.TerrenoId" />
                    <div class="form-group">
                        <label for="usernameToDelete">Nome Utente Collaboratore da Eliminare:</label>
                        <input type="text" class="form-control" id="usernameToDelete" name="usernameToDelete" required>
                    </div>
                    <br />
                    <button type="submit" class="btn btn-danger">Elimina</button>
                </form>
            </div>
        </div>
    </div>
</div>